// <auto-generated />
using System;
using CafeBarrio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeBarrio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CafeBarrioDbContext))]
    [Migration("20260605165450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeBarrio.Domain.Entities.CategoriaCafe", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId");

                    b.ToTable("CategoriaCafe", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int?>("CategoriaPrefId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_pref_id");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo_cliente");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoClienteId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_cliente_id");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_documento");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("ClienteId");

                    b.HasIndex("CategoriaPrefId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.DetalleTransaccion", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("SubtotalLinea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_linea");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("DetalleTransaccion", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.OpcionEnvio", b =>
                {
                    b.Property<int>("OpcionEnvioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opcion_envio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionEnvioId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Tarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tarifa");

                    b.HasKey("OpcionEnvioId");

                    b.ToTable("OpcionEnvio", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_disponible");

                    b.Property<string>("CantidadPorUnidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cantidad_por_unidad");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsMayorista")
                        .HasColumnType("bit")
                        .HasColumnName("es_mayorista");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sede_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("distrito");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit")
                        .HasColumnName("es_principal");

                    b.Property<DateOnly?>("FechaApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_apertura");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("SedeId");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TipoCliente", b =>
                {
                    b.Property<int>("TipoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tipo_cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoClienteId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoClienteId");

                    b.ToTable("TipoCliente", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("canal");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_envio");

                    b.Property<bool>("EsMayorista")
                        .HasColumnType("bit")
                        .HasColumnName("es_mayorista");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Impuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("impuesto");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notas");

                    b.Property<int?>("OpcionEnvioId")
                        .HasColumnType("int")
                        .HasColumnName("opcion_envio_id");

                    b.Property<int>("SedeId")
                        .HasColumnType("int")
                        .HasColumnName("sede_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("TransaccionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("OpcionEnvioId");

                    b.HasIndex("SedeId");

                    b.ToTable("Transaccion", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TransaccionMayorista", b =>
                {
                    b.Property<int>("TmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TmId"));

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_estimada");

                    b.Property<string>("InstruccionesEntrega")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instrucciones_entrega");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    b.Property<int?>("TransporteId")
                        .HasColumnType("int")
                        .HasColumnName("transporte_id");

                    b.HasKey("TmId");

                    b.HasIndex("TransaccionId")
                        .IsUnique();

                    b.HasIndex("TransporteId");

                    b.ToTable("TransaccionMayorista", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transporte_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<decimal?>("CapacidadKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacidad_kg");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("placa");

                    b.HasKey("TransporteId");

                    b.ToTable("Transporte", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.UbicacionPreferencia", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ubicacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UbicacionId");

                    b.ToTable("UbicacionPreferencia", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.CategoriaCafe", "CategoriaPreferida")
                        .WithMany("ClientesConPreferencia")
                        .HasForeignKey("CategoriaPrefId");

                    b.HasOne("CafeBarrio.Domain.Entities.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.UbicacionPreferencia", "Ubicacion")
                        .WithMany("Clientes")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("CategoriaPreferida");

                    b.Navigation("TipoCliente");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.DetalleTransaccion", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Transaccion", "Transaccion")
                        .WithMany("Detalles")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.CategoriaCafe", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Transacciones")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.OpcionEnvio", "OpcionEnvio")
                        .WithMany("Transacciones")
                        .HasForeignKey("OpcionEnvioId");

                    b.HasOne("CafeBarrio.Domain.Entities.Sede", "Sede")
                        .WithMany("Transacciones")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("OpcionEnvio");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TransaccionMayorista", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Transaccion", "Transaccion")
                        .WithOne("TransaccionMayorista")
                        .HasForeignKey("CafeBarrio.Domain.Entities.TransaccionMayorista", "TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Transporte", "Transporte")
                        .WithMany("TransaccionesMayoristas")
                        .HasForeignKey("TransporteId");

                    b.Navigation("Transaccion");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.CategoriaCafe", b =>
                {
                    b.Navigation("ClientesConPreferencia");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.OpcionEnvio", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("TransaccionMayorista");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transporte", b =>
                {
                    b.Navigation("TransaccionesMayoristas");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.UbicacionPreferencia", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
