// <auto-generated />
using System;
using CafeBarrio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeBarrio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CafeBarrioDbContext))]
    [Migration("20260611175225_AddUsuarioLockout")]
    partial class AddUsuarioLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Anulacion", b =>
                {
                    b.Property<int>("AnulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnulacionId"));

                    b.Property<int>("AutorizadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ImpactoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MetodoDevolucion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontoDevuelto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoOriginal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OperadorSolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAnulacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnulacionId");

                    b.HasIndex("AutorizadorId");

                    b.HasIndex("OperadorSolicitanteId");

                    b.HasIndex("TransaccionId")
                        .IsUnique();

                    b.ToTable("Anulacion", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.CategoriaCafe", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId");

                    b.ToTable("CategoriaCafe", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int?>("CategoriaPrefId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_pref_id");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo_cliente");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoClienteId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_cliente_id");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_documento");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("ClienteId");

                    b.HasIndex("CategoriaPrefId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.ConfiguracionNegocio", b =>
                {
                    b.Property<int>("ConfiguracionNegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionNegocioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaIGV")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("TasaIPM")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("ConfiguracionNegocioId");

                    b.HasIndex("SedeId", "Activo");

                    b.ToTable("ConfiguracionNegocio", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.DetalleTransaccion", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("SubtotalLinea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_linea");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("DetalleTransaccion", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_IdempotencyRecords_Key");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<bool>("EsEfectivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoCajaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovimientoCajaId");

                    b.HasIndex("TurnoId");

                    b.ToTable("MovimientoCaja", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.OpcionEnvio", b =>
                {
                    b.Property<int>("OpcionEnvioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opcion_envio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionEnvioId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Tarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tarifa");

                    b.HasKey("OpcionEnvioId");

                    b.ToTable("OpcionEnvio", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Operador", b =>
                {
                    b.Property<int>("OperadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperadorId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("OperadorId");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Operadores_Activo");

                    b.HasIndex("SedeId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Operador_UsuarioId");

                    b.ToTable("Operador", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("cantidad_disponible");

                    b.Property<string>("CantidadPorUnidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cantidad_por_unidad");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsMayorista")
                        .HasColumnType("bit")
                        .HasColumnName("es_mayorista");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SeguimientoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("seguimiento_inventario");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("unidad")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoId");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Productos_Activo");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Productos_CategoriaId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sede_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("distrito");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit")
                        .HasColumnName("es_principal");

                    b.Property<DateOnly?>("FechaApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_apertura");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("SedeId");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TipoCliente", b =>
                {
                    b.Property<int>("TipoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tipo_cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoClienteId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoClienteId");

                    b.ToTable("TipoCliente", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("POS")
                        .HasColumnName("canal");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_envio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsMayorista")
                        .HasColumnType("bit")
                        .HasColumnName("es_mayorista");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("Impuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("impuesto");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago_id");

                    b.Property<int?>("MetodoPagoSecundarioId")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago_secundario_id");

                    b.Property<decimal?>("MontoMetodoPrimario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_metodo_primario");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_documento");

                    b.Property<int?>("OpcionEnvioId")
                        .HasColumnType("int")
                        .HasColumnName("opcion_envio_id");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("int")
                        .HasColumnName("operador_id");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razon_social");

                    b.Property<decimal>("RecargoPropina")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("recargo_propina");

                    b.Property<int>("SedeId")
                        .HasColumnType("int")
                        .HasColumnName("sede_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("SunatError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunatEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SunatIntentos")
                        .HasColumnType("int");

                    b.Property<string>("SunatNumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_documento");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int")
                        .HasColumnName("turno_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransaccionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Transacciones_Fecha");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Transacciones_IdempotencyKey")
                        .HasFilter("[idempotency_key] IS NOT NULL");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("MetodoPagoSecundarioId");

                    b.HasIndex("OpcionEnvioId");

                    b.HasIndex("OperadorId")
                        .HasDatabaseName("IX_Transacciones_OperadorId");

                    b.HasIndex("TurnoId")
                        .HasDatabaseName("IX_Transacciones_TurnoId");

                    b.HasIndex("Fecha", "OperadorId")
                        .HasDatabaseName("IX_Transacciones_Fecha_OperadorId");

                    b.HasIndex("SedeId", "Fecha")
                        .HasDatabaseName("IX_Transaccion_SedeId_Fecha");

                    b.ToTable("Transaccion", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TransaccionMayorista", b =>
                {
                    b.Property<int>("TmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TmId"));

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_estimada");

                    b.Property<string>("InstruccionesEntrega")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instrucciones_entrega");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int")
                        .HasColumnName("transaccion_id");

                    b.Property<int?>("TransporteId")
                        .HasColumnType("int")
                        .HasColumnName("transporte_id");

                    b.HasKey("TmId");

                    b.HasIndex("TransaccionId")
                        .IsUnique();

                    b.HasIndex("TransporteId");

                    b.ToTable("TransaccionMayorista", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transporte_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<decimal?>("CapacidadKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacidad_kg");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit")
                        .HasColumnName("disponible");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("placa");

                    b.HasKey("TransporteId");

                    b.ToTable("Transporte", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierto");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoApertura")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MontoEfectivoCierto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAnulacionesEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalEfectivoSistema")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalMovimientosEntrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMovimientosSalida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVentasEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurnoId");

                    b.HasIndex("FechaApertura")
                        .HasDatabaseName("IX_Turnos_FechaApertura");

                    b.HasIndex("OperadorId")
                        .HasDatabaseName("IX_Turnos_OperadorId");

                    b.HasIndex("SedeId");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.UbicacionPreferencia", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ubicacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UbicacionId");

                    b.ToTable("UbicacionPreferencia", (string)null);
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Anulacion", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Operador", "Autorizador")
                        .WithMany("AnulacionesAutorizadas")
                        .HasForeignKey("AutorizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Operador", "OperadorSolicitante")
                        .WithMany("AnulacionesSolicitadas")
                        .HasForeignKey("OperadorSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Transaccion", "Transaccion")
                        .WithOne("Anulacion")
                        .HasForeignKey("CafeBarrio.Domain.Entities.Anulacion", "TransaccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autorizador");

                    b.Navigation("OperadorSolicitante");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.CategoriaCafe", "CategoriaPreferida")
                        .WithMany("ClientesConPreferencia")
                        .HasForeignKey("CategoriaPrefId");

                    b.HasOne("CafeBarrio.Domain.Entities.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.UbicacionPreferencia", "Ubicacion")
                        .WithMany("Clientes")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("CategoriaPreferida");

                    b.Navigation("TipoCliente");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.ConfiguracionNegocio", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.DetalleTransaccion", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Transaccion", "Transaccion")
                        .WithMany("Detalles")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Turno", "Turno")
                        .WithMany("Movimientos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Operador", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sede");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.CategoriaCafe", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeBarrio.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Transacciones")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.MetodoPago", "MetodoPagoSecundario")
                        .WithMany()
                        .HasForeignKey("MetodoPagoSecundarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CafeBarrio.Domain.Entities.OpcionEnvio", "OpcionEnvio")
                        .WithMany("Transacciones")
                        .HasForeignKey("OpcionEnvioId");

                    b.HasOne("CafeBarrio.Domain.Entities.Operador", "Operador")
                        .WithMany("Transacciones")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CafeBarrio.Domain.Entities.Sede", "Sede")
                        .WithMany("Transacciones")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Turno", "Turno")
                        .WithMany("Transacciones")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("MetodoPagoSecundario");

                    b.Navigation("OpcionEnvio");

                    b.Navigation("Operador");

                    b.Navigation("Sede");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TransaccionMayorista", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Transaccion", "Transaccion")
                        .WithOne("TransaccionMayorista")
                        .HasForeignKey("CafeBarrio.Domain.Entities.TransaccionMayorista", "TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Transporte", "Transporte")
                        .WithMany("TransaccionesMayoristas")
                        .HasForeignKey("TransporteId");

                    b.Navigation("Transaccion");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Turno", b =>
                {
                    b.HasOne("CafeBarrio.Domain.Entities.Operador", "Operador")
                        .WithMany("Turnos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeBarrio.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.CategoriaCafe", b =>
                {
                    b.Navigation("ClientesConPreferencia");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.OpcionEnvio", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Operador", b =>
                {
                    b.Navigation("AnulacionesAutorizadas");

                    b.Navigation("AnulacionesSolicitadas");

                    b.Navigation("Transacciones");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transaccion", b =>
                {
                    b.Navigation("Anulacion");

                    b.Navigation("Detalles");

                    b.Navigation("TransaccionMayorista");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Transporte", b =>
                {
                    b.Navigation("TransaccionesMayoristas");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("CafeBarrio.Domain.Entities.UbicacionPreferencia", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
